application:
  port: 8000
  host: "127.0.0.1"
database:
  username: "postgres"
  password: "password"
  port: 5432
  host: "localhost"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@example.com"
  authorization_token: "dummy-secret-token"
  timeout_milliseconds: 10000